# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImporterUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(799, 728)
        self.tableNameField = QtGui.QLineEdit(Dialog)
        self.tableNameField.setGeometry(QtCore.QRect(80, 30, 581, 21))
        self.tableNameField.setObjectName(_fromUtf8("tableNameField"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(15, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(340, 55, 66, 16))
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(320, 80, 86, 16))
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(725, 30, 46, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(5, 5, 91, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tableNameCount = QtGui.QLineEdit(Dialog)
        self.tableNameCount.setEnabled(False)
        self.tableNameCount.setGeometry(QtCore.QRect(670, 30, 46, 20))
        self.tableNameCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableNameCount.setText(_fromUtf8(""))
        self.tableNameCount.setMaxLength(6)
        self.tableNameCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableNameCount.setReadOnly(True)
        self.tableNameCount.setObjectName(_fromUtf8("tableNameCount"))
        self.lineEdit_3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(415, 55, 351, 20))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(415, 80, 351, 20))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(80, 55, 236, 46))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButtonSed = QtGui.QRadioButton(self.groupBox)
        self.radioButtonSed.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButtonSed.setObjectName(_fromUtf8("radioButtonSed"))
        self.radioButtonIgnMet = QtGui.QRadioButton(self.groupBox)
        self.radioButtonIgnMet.setGeometry(QtCore.QRect(100, 20, 141, 17))
        self.radioButtonIgnMet.setObjectName(_fromUtf8("radioButtonIgnMet"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 105, 61, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 125, 91, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(15, 150, 106, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 175, 91, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(30, 200, 91, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.masterPathField = QtGui.QLineEdit(Dialog)
        self.masterPathField.setGeometry(QtCore.QRect(125, 105, 641, 20))
        self.masterPathField.setObjectName(_fromUtf8("masterPathField"))
        self.masterDatasetField = QtGui.QLineEdit(Dialog)
        self.masterDatasetField.setGeometry(QtCore.QRect(125, 130, 411, 20))
        self.masterDatasetField.setObjectName(_fromUtf8("masterDatasetField"))
        self.lineEdit_7 = QtGui.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(125, 155, 641, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(Dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(125, 180, 641, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(125, 205, 641, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(540, 130, 31, 16))
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.masterDatasetDate = QtGui.QLineEdit(Dialog)
        self.masterDatasetDate.setEnabled(True)
        self.masterDatasetDate.setGeometry(QtCore.QRect(580, 130, 81, 20))
        self.masterDatasetDate.setObjectName(_fromUtf8("masterDatasetDate"))
        self.radioButtonTest = QtGui.QRadioButton(Dialog)
        self.radioButtonTest.setGeometry(QtCore.QRect(150, 5, 46, 17))
        self.radioButtonTest.setObjectName(_fromUtf8("radioButtonTest"))
        self.activeButtonGroup = QtGui.QButtonGroup(Dialog)
        self.activeButtonGroup.setObjectName(_fromUtf8("activeButtonGroup"))
        self.activeButtonGroup.addButton(self.radioButtonTest)
        self.radioButtonLive = QtGui.QRadioButton(Dialog)
        self.radioButtonLive.setGeometry(QtCore.QRect(105, 5, 46, 17))
        self.radioButtonLive.setObjectName(_fromUtf8("radioButtonLive"))
        self.activeButtonGroup.addButton(self.radioButtonLive)
        self.masterDatasetCount = QtGui.QLineEdit(Dialog)
        self.masterDatasetCount.setEnabled(False)
        self.masterDatasetCount.setGeometry(QtCore.QRect(670, 130, 46, 20))
        self.masterDatasetCount.setMaxLength(6)
        self.masterDatasetCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.masterDatasetCount.setReadOnly(True)
        self.masterDatasetCount.setObjectName(_fromUtf8("masterDatasetCount"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(725, 130, 46, 16))
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(30, 220, 91, 31))
        self.label_13.setLineWidth(1)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(30, 250, 91, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(30, 315, 91, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(30, 425, 91, 21))
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(30, 535, 91, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lineEdit_12 = QtGui.QLineEdit(Dialog)
        self.lineEdit_12.setGeometry(QtCore.QRect(125, 230, 641, 20))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lineEdit_13 = QtGui.QLineEdit(Dialog)
        self.lineEdit_13.setGeometry(QtCore.QRect(125, 255, 411, 20))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(Dialog)
        self.lineEdit_14.setEnabled(False)
        self.lineEdit_14.setGeometry(QtCore.QRect(670, 255, 46, 20))
        self.lineEdit_14.setMaxLength(6)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(540, 255, 31, 16))
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_15 = QtGui.QLineEdit(Dialog)
        self.lineEdit_15.setEnabled(True)
        self.lineEdit_15.setGeometry(QtCore.QRect(580, 255, 81, 20))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(725, 255, 46, 16))
        self.label_19.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.plainTextEdit = QtGui.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(125, 280, 536, 106))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(125, 390, 536, 106))
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(Dialog)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(125, 500, 536, 106))
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(10, 640, 111, 41))
        self.label_20.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(Dialog)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(125, 610, 536, 106))
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(679, 280, 81, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(679, 310, 81, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(670, 340, 101, 376))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 20, 81, 36))
        self.pushButton_3.setText(_fromUtf8("Archive\n"
" Master"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 60, 81, 51))
        self.pushButton_4.setText(_fromUtf8("Create\n"
" Standard\n"
" Input Data"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 115, 81, 51))
        self.pushButton_5.setText(_fromUtf8("Update\n"
" Field Data"))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 170, 81, 36))
        self.pushButton_6.setText(_fromUtf8("Update\n"
" Field Data"))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 330, 81, 36))
        self.pushButton_7.setText(_fromUtf8("Archive\n"
"Input Data"))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 210, 81, 116))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.groupBox.raise_()
        self.tableNameField.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.tableNameCount.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.label_2.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.masterPathField.raise_()
        self.masterDatasetField.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.label_11.raise_()
        self.masterDatasetDate.raise_()
        self.radioButtonTest.raise_()
        self.radioButtonLive.raise_()
        self.masterDatasetCount.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_14.raise_()
        self.label_18.raise_()
        self.lineEdit_15.raise_()
        self.label_19.raise_()
        self.plainTextEdit.raise_()
        self.plainTextEdit_2.raise_()
        self.plainTextEdit_3.raise_()
        self.label_20.raise_()
        self.plainTextEdit_4.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.groupBox_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.tableNameField.setText(_translate("Dialog", "Sheet1$", None))
        self.label.setText(_translate("Dialog", "Table Name", None))
        self.label_3.setText(_translate("Dialog", "Key Field", None))
        self.label_4.setText(_translate("Dialog", "Parent Key Field", None))
        self.label_5.setText(_translate("Dialog", "Records", None))
        self.label_6.setText(_translate("Dialog", "Active Dataset:", None))
        self.groupBox.setTitle(_translate("Dialog", "Sedimentary or Igneous/Metamorphic", None))
        self.radioButtonSed.setText(_translate("Dialog", "Sedimentary", None))
        self.radioButtonIgnMet.setText(_translate("Dialog", "Igneous/Metamorphic", None))
        self.label_2.setText(_translate("Dialog", "Master Path", None))
        self.label_7.setText(_translate("Dialog", "Master Dataset", None))
        self.label_8.setText(_translate("Dialog", "Master Data Archive", None))
        self.label_9.setText(_translate("Dialog", "Project Path", None))
        self.label_10.setText(_translate("Dialog", "Input Path", None))
        self.label_11.setText(_translate("Dialog", "Date", None))
        self.masterDatasetDate.setText(_translate("Dialog", "2017/08/02", None))
        self.radioButtonTest.setText(_translate("Dialog", "Test", None))
        self.radioButtonLive.setText(_translate("Dialog", "Live", None))
        self.masterDatasetCount.setText(_translate("Dialog", "888888", None))
        self.label_12.setText(_translate("Dialog", "Records", None))
        self.label_13.setText(_translate("Dialog", "Temporary Master Dataset", None))
        self.label_14.setText(_translate("Dialog", "Archive Path", None))
        self.label_15.setText(_translate("Dialog", "Mismatched Fields", None))
        self.label_16.setText(_translate("Dialog", "Key Fields Check", None))
        self.label_17.setText(_translate("Dialog", "Matching Records", None))
        self.lineEdit_14.setText(_translate("Dialog", "888888", None))
        self.label_18.setText(_translate("Dialog", "Date", None))
        self.lineEdit_15.setText(_translate("Dialog", "2017/08/02", None))
        self.label_19.setText(_translate("Dialog", "Records", None))
        self.label_20.setText(_translate("Dialog", "Python Command (Paste into Python Window)", None))
        self.pushButton.setText(_translate("Dialog", "Check Data", None))
        self.pushButton_2.setText(_translate("Dialog", "Refresh", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Python Commands", None))
        self.pushButton_8.setText(_translate("Dialog", "Append Data\n"
" to Master &\n"
"Create Temp\n"
"Master in \n"
"Input\n"
" Database", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

