# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImporterUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(661, 286)
        self.inputField = QtGui.QLineEdit(Dialog)
        self.inputField.setEnabled(False)
        self.inputField.setGeometry(QtCore.QRect(120, 79, 421, 21))
        self.inputField.setText(_fromUtf8(""))
        self.inputField.setMaxLength(70)
        self.inputField.setReadOnly(True)
        self.inputField.setObjectName(_fromUtf8("inputField"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(605, 80, 46, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.inputCount = QtGui.QLineEdit(Dialog)
        self.inputCount.setEnabled(False)
        self.inputCount.setGeometry(QtCore.QRect(550, 80, 46, 20))
        self.inputCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputCount.setText(_fromUtf8(""))
        self.inputCount.setMaxLength(6)
        self.inputCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputCount.setReadOnly(True)
        self.inputCount.setObjectName(_fromUtf8("inputCount"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 5, 236, 46))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButtonsedimentary = QtGui.QRadioButton(self.groupBox)
        self.radioButtonsedimentary.setEnabled(False)
        self.radioButtonsedimentary.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButtonsedimentary.setObjectName(_fromUtf8("radioButtonsedimentary"))
        self.ignSedButtonGroup = QtGui.QButtonGroup(Dialog)
        self.ignSedButtonGroup.setObjectName(_fromUtf8("ignSedButtonGroup"))
        self.ignSedButtonGroup.addButton(self.radioButtonsedimentary)
        self.radioButtonigneous = QtGui.QRadioButton(self.groupBox)
        self.radioButtonigneous.setEnabled(False)
        self.radioButtonigneous.setGeometry(QtCore.QRect(100, 20, 141, 17))
        self.radioButtonigneous.setObjectName(_fromUtf8("radioButtonigneous"))
        self.ignSedButtonGroup.addButton(self.radioButtonigneous)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 125, 101, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(5, 50, 106, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(0, 150, 111, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.destinationField = QtGui.QLineEdit(Dialog)
        self.destinationField.setEnabled(False)
        self.destinationField.setGeometry(QtCore.QRect(120, 105, 421, 20))
        self.destinationField.setMaxLength(70)
        self.destinationField.setReadOnly(True)
        self.destinationField.setObjectName(_fromUtf8("destinationField"))
        self.projectPathField = QtGui.QLineEdit(Dialog)
        self.projectPathField.setEnabled(False)
        self.projectPathField.setGeometry(QtCore.QRect(120, 55, 476, 20))
        self.projectPathField.setReadOnly(True)
        self.projectPathField.setObjectName(_fromUtf8("projectPathField"))
        self.tempField = QtGui.QLineEdit(Dialog)
        self.tempField.setEnabled(False)
        self.tempField.setGeometry(QtCore.QRect(120, 155, 421, 20))
        self.tempField.setMaxLength(70)
        self.tempField.setReadOnly(True)
        self.tempField.setObjectName(_fromUtf8("tempField"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(25, 100, 86, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(255, 5, 396, 46))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.radioButtonsample = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonsample.setEnabled(False)
        self.radioButtonsample.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButtonsample.setObjectName(_fromUtf8("radioButtonsample"))
        self.dataButtonGroup = QtGui.QButtonGroup(Dialog)
        self.dataButtonGroup.setObjectName(_fromUtf8("dataButtonGroup"))
        self.dataButtonGroup.addButton(self.radioButtonsample)
        self.radioButtonage = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonage.setEnabled(False)
        self.radioButtonage.setGeometry(QtCore.QRect(80, 20, 96, 17))
        self.radioButtonage.setObjectName(_fromUtf8("radioButtonage"))
        self.dataButtonGroup.addButton(self.radioButtonage)
        self.radioButtonanalysis = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonanalysis.setEnabled(False)
        self.radioButtonanalysis.setGeometry(QtCore.QRect(180, 20, 106, 17))
        self.radioButtonanalysis.setObjectName(_fromUtf8("radioButtonanalysis"))
        self.dataButtonGroup.addButton(self.radioButtonanalysis)
        self.radioButtonexcel = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonexcel.setEnabled(False)
        self.radioButtonexcel.setGeometry(QtCore.QRect(290, 20, 106, 17))
        self.radioButtonexcel.setObjectName(_fromUtf8("radioButtonexcel"))
        self.dataButtonGroup.addButton(self.radioButtonexcel)
        self.destinationCount = QtGui.QLineEdit(Dialog)
        self.destinationCount.setEnabled(False)
        self.destinationCount.setGeometry(QtCore.QRect(550, 105, 46, 20))
        self.destinationCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.destinationCount.setText(_fromUtf8(""))
        self.destinationCount.setMaxLength(6)
        self.destinationCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.destinationCount.setReadOnly(True)
        self.destinationCount.setObjectName(_fromUtf8("destinationCount"))
        self.tempCount = QtGui.QLineEdit(Dialog)
        self.tempCount.setEnabled(False)
        self.tempCount.setGeometry(QtCore.QRect(550, 155, 46, 20))
        self.tempCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tempCount.setText(_fromUtf8(""))
        self.tempCount.setMaxLength(6)
        self.tempCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempCount.setReadOnly(True)
        self.tempCount.setObjectName(_fromUtf8("tempCount"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(605, 105, 46, 16))
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_22 = QtGui.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(605, 156, 46, 16))
        self.label_22.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.pushButtonSavePath = QtGui.QPushButton(Dialog)
        self.pushButtonSavePath.setGeometry(QtCore.QRect(605, 54, 46, 22))
        self.pushButtonSavePath.setObjectName(_fromUtf8("pushButtonSavePath"))
        self.pushButtonProceed = QtGui.QPushButton(Dialog)
        self.pushButtonProceed.setGeometry(QtCore.QRect(255, 235, 146, 41))
        self.pushButtonProceed.setObjectName(_fromUtf8("pushButtonProceed"))
        self.destinationFilenameField = QtGui.QLineEdit(Dialog)
        self.destinationFilenameField.setEnabled(False)
        self.destinationFilenameField.setGeometry(QtCore.QRect(120, 130, 531, 20))
        self.destinationFilenameField.setMaxLength(70)
        self.destinationFilenameField.setReadOnly(True)
        self.destinationFilenameField.setObjectName(_fromUtf8("destinationFilenameField"))
        self.pushButtonBackupPath = QtGui.QPushButton(Dialog)
        self.pushButtonBackupPath.setGeometry(QtCore.QRect(605, 180, 46, 22))
        self.pushButtonBackupPath.setObjectName(_fromUtf8("pushButtonBackupPath"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(15, 177, 96, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.backupPathField = QtGui.QLineEdit(Dialog)
        self.backupPathField.setEnabled(False)
        self.backupPathField.setGeometry(QtCore.QRect(120, 180, 476, 20))
        self.backupPathField.setMaxLength(70)
        self.backupPathField.setReadOnly(True)
        self.backupPathField.setObjectName(_fromUtf8("backupPathField"))
        self.backupNameField = QtGui.QLineEdit(Dialog)
        self.backupNameField.setEnabled(False)
        self.backupNameField.setGeometry(QtCore.QRect(120, 205, 531, 20))
        self.backupNameField.setMaxLength(70)
        self.backupNameField.setReadOnly(True)
        self.backupNameField.setObjectName(_fromUtf8("backupNameField"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(25, 200, 86, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.groupBox.raise_()
        self.inputField.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.inputCount.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.destinationField.raise_()
        self.projectPathField.raise_()
        self.tempField.raise_()
        self.label_14.raise_()
        self.groupBox_3.raise_()
        self.destinationCount.raise_()
        self.tempCount.raise_()
        self.label_18.raise_()
        self.label_22.raise_()
        self.pushButtonSavePath.raise_()
        self.pushButtonProceed.raise_()
        self.destinationFilenameField.raise_()
        self.pushButtonBackupPath.raise_()
        self.label_13.raise_()
        self.backupPathField.raise_()
        self.backupNameField.raise_()
        self.label_9.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButtonSavePath, self.pushButtonBackupPath)
        Dialog.setTabOrder(self.pushButtonBackupPath, self.projectPathField)
        Dialog.setTabOrder(self.projectPathField, self.tempField)
        Dialog.setTabOrder(self.tempField, self.tempCount)
        Dialog.setTabOrder(self.tempCount, self.destinationCount)
        Dialog.setTabOrder(self.destinationCount, self.inputCount)
        Dialog.setTabOrder(self.inputCount, self.radioButtonsedimentary)
        Dialog.setTabOrder(self.radioButtonsedimentary, self.radioButtonigneous)
        Dialog.setTabOrder(self.radioButtonigneous, self.radioButtonsample)
        Dialog.setTabOrder(self.radioButtonsample, self.radioButtonage)
        Dialog.setTabOrder(self.radioButtonage, self.radioButtonanalysis)
        Dialog.setTabOrder(self.radioButtonanalysis, self.radioButtonexcel)
        Dialog.setTabOrder(self.radioButtonexcel, self.backupPathField)
        Dialog.setTabOrder(self.backupPathField, self.inputField)
        Dialog.setTabOrder(self.inputField, self.backupNameField)
        Dialog.setTabOrder(self.backupNameField, self.destinationField)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Input Layer", None))
        self.label_5.setText(_translate("Dialog", "Lines", None))
        self.groupBox.setTitle(_translate("Dialog", "Sedimentary or Igneous/Metamorphic", None))
        self.radioButtonsedimentary.setText(_translate("Dialog", "Sedimentary", None))
        self.radioButtonigneous.setText(_translate("Dialog", "Igneous/Metamorphic", None))
        self.label_7.setText(_translate("Dialog", "Destination Filename", None))
        self.label_8.setText(_translate("Dialog", "Project Save Path", None))
        self.label_10.setText(_translate("Dialog", "Temporary Layer", None))
        self.label_14.setText(_translate("Dialog", "Destination", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Data Type", None))
        self.radioButtonsample.setText(_translate("Dialog", "Samples", None))
        self.radioButtonage.setText(_translate("Dialog", "Summary Ages", None))
        self.radioButtonanalysis.setText(_translate("Dialog", "Sample Analyses", None))
        self.radioButtonexcel.setText(_translate("Dialog", "Raw Excel Data", None))
        self.label_18.setText(_translate("Dialog", "Lines", None))
        self.label_22.setText(_translate("Dialog", "Lines", None))
        self.pushButtonSavePath.setText(_translate("Dialog", "Open", None))
        self.pushButtonProceed.setText(_translate("Dialog", "Proceed With Merge", None))
        self.pushButtonBackupPath.setText(_translate("Dialog", "Open", None))
        self.label_13.setText(_translate("Dialog", "Backup Path", None))
        self.label_9.setText(_translate("Dialog", "Backup Filename", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

